###############################################################################
#                            Based on phpdocker.io                            #
###############################################################################
version: '3.1'
services:
    postgres:
        build: 'phpdocker/postgres'
        container_name: testing-neighbour-states-symfony-postgres
        working_dir: /application
        volumes:
            - './application:/application'
            - './postgres:/var/lib/postgresql'
        environment:
            - POSTGRES_USER=neighbour-states-acc
            - POSTGRES_PASSWORD=thisoneshouldnotbeusedfornormalpurposesonsystem
            - POSTGRES_DB=testing_neighbour_states_symfony
            - POSTGRES_PASS=thisoneshouldnotbeusedfornormalpurposesonsystem
            - POSTGRES_DBNAME=testing-neighbour-states-symfony
        ports:
            - '65432:5432'
        networks:
            - 'neighbour-net-symfony'

    webserver:
        restart: always
        build: phpdocker/nginx
        container_name: testing-neighbour-states-symfony-web
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '40500:80'
            - '40509:89'
        networks:
            - 'neighbour-net-symfony'

    php-fpm8:
        build: phpdocker/php-fpm8
        container_name: testing-neighbour-states-symfony-php8
        working_dir: /application
        volumes:
            - './application:/application'
            - './phpdocker/php-fpm8/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        environment:
            - SESSION_DOMAIN=localhost
            - SYSTEM_DATABASE=postgresql://neighbour-states-acc:thisoneshouldnotbeusedfornormalpurposesonsystem@testing-neighbour-states-symfony-postgres:5432/testing_neighbour_states_symfony?serverVersion=11&charset=utf8
        networks:
            - 'neighbour-net-symfony'

    php-adminer:
        build: phpdocker/php-fpm7
        container_name: testing-neighbour-states-symfony-adminer
        working_dir: /application
        volumes:
            - './adminer:/application'
            - './phpdocker/php-fpm7/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
        networks:
            - 'neighbour-net-symfony'


networks:
    neighbour-net-symfony:
        driver: bridge
